export const MAIL_QUEUE = 'MAIL_QUEUE';
export const SENT_OTP = 'SENT_OTP';
export const SENT_USER_URL = 'SENT_USER_URL';
export const WELCOME_MSG = 'WELCOME_MSG';
export const BENEFICIARY_ADDED = 'BENEFICIARY_ADDED';
export const BENEFICIARY_ASSIGNED_TOKEN = 'BENEFICIARY_ASSIGNED_TOKEN';
