name: Main CI/CD
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
env:
  CI: false
  env_main: ${{ secrets.ENV_MAIN }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

    #   - name: import env file
    #     run: |
    #       touch ./.env && echo "$env_main" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Image
      - name: build && push kii-backend
        id: build-push-kii-backend
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha,scope=${{ github.ref_name }}-kii-backend
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-kii-backend
          file: Dockerfile
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: | 
            thespiritman/kiiChain-backend:${{ github.sha }}
            thespiritman/kiiChain-backend:main
                    
      # - name: Update Docker Image Tag
      #   uses: appleboy/ssh-action@v0.1.3
      #   if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       export IMAGE_TAG=${{ github.sha }}
      #       cd /home/ubuntu/docker-projects/kiiChain/kiiChain-core && docker pull thespiritman/kiiChain-backend:$IMAGE_TAG && docker rm kii_be -f && docker compose up kii_be -d && docker image prune -f